# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/HP/Desktop/loopback_2nd_v/loopback_2nd_v.srcs/sources_1/ip/felix_gtp0/felix_gtp0.xci
# IP: The module: 'felix_gtp0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/Desktop/loopback_2nd_v/loopback_2nd_v.srcs/sources_1/ip/felix_gtp0/felix_gtp0.xdc
# XDC: The top module name and the constraint reference have the same name: 'felix_gtp0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/HP/Desktop/loopback_2nd_v/loopback_2nd_v.srcs/sources_1/ip/felix_gtp0/felix_gtp0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'felix_gtp0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/HP/Desktop/loopback_2nd_v/loopback_2nd_v.srcs/sources_1/ip/felix_gtp0/felix_gtp0.xci
# IP: The module: 'felix_gtp0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/Desktop/loopback_2nd_v/loopback_2nd_v.srcs/sources_1/ip/felix_gtp0/felix_gtp0.xdc
# XDC: The top module name and the constraint reference have the same name: 'felix_gtp0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/HP/Desktop/loopback_2nd_v/loopback_2nd_v.srcs/sources_1/ip/felix_gtp0/felix_gtp0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'felix_gtp0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
