# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/HP/Documents/DUNE at CERN/codigo/constrs_1/new/constraints.xdc

# IP: C:/Users/HP/Documents/DUNE at CERN/FullMode_Integration_Speed_3/FullMode_Integration_Speed_3.srcs/sources_1/ip/MMCM_GTP_1/MMCM_GTP.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MMCM_GTP || ORIG_REF_NAME==MMCM_GTP} -quiet] -quiet
